# Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wso2apim-analytics-deployment
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: wso2apim-analytics
    spec:
      containers:
      - name: wso2apim-analytics
        image: gcr.io/research-n-development-209206/wso2am-analytics:2.6.0
        resources:
          limits:
            memory: "4Gi"
          requests:
            memory: "4Gi"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - nc -z localhost 7712
          initialDelaySeconds: 250
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - nc -z localhost 7712
          initialDelaySeconds: 250
          periodSeconds: 10
        lifecycle:
          preStop:
            exec:
              command:  ['sh', '-c', '${WSO2_SERVER_HOME}/bin/worker.sh stop']
        imagePullPolicy: Always
        securityContext:
          runAsUser: 802
        ports:
        -
          containerPort: 9764
          protocol: "TCP"
        -
          containerPort: 9444
          protocol: "TCP"
        -
          containerPort: 7612
          protocol: "TCP"
        -
          containerPort: 7712
          protocol: "TCP"
        -
          containerPort: 11225
          protocol: "TCP"
        -
          containerPort: 10006
          protocol: "TCP"
        -
          containerPort: 11001
          protocol: "TCP"
        -
          containerPort: 11002
          protocol: "TCP"
        -
          containerPort: 11003
          protocol: "TCP"
        -
          containerPort: 11501
          protocol: "TCP"
        -
          containerPort: 8083
          protocol: "TCP"
        -
          containerPort: 4041
          protocol: "TCP"
        -
          containerPort: 10007
          protocol: TCP
        -
          containerPort: 12501
          protocol: TCP
        -
          containerPort: 13001
          protocol: TCP
        -
          containerPort: 13501
          protocol: TCP
        -
          containerPort: 14501
          protocol: TCP
        -
          containerPort: 7078
          protocol: TCP
        -
          containerPort: 6067
          protocol: TCP
        volumeMounts:
        - name: apim-analytics-conf-worker
          mountPath: /home/wso2carbon/wso2-config-volume/conf/worker
      serviceAccountName: "wso2svc-account"
#      imagePullSecrets:
#      - name: wso2creds
      volumes:
      - name: apim-analytics-conf-worker
        configMap:
          name: apim-analytics-conf-worker
