
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2am-pattern-1-analytics-worker-deployment
  namespace: wso2
spec:
  replicas: 1
  minReadySeconds: 75
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      deployment: wso2am-pattern-1-analytics-worker
      product: api-manager
  template:
    metadata:
      labels:
        deployment: wso2am-pattern-1-analytics-worker
        product: api-manager
    spec:
      initContainers:
        - name: init-apim-analytics-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z wso2apim-rdbms-service-mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL Server has started";']
      containers:
        - name: wso2am-pattern-1-analytics-worker
          image: "$image.pull.@.wso2"/wso2am-analytics-worker:3.0.0
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 9444
            initialDelaySeconds: 100
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 9444
            initialDelaySeconds: 100
            periodSeconds: 10
          lifecycle:
            preStop:
              exec:
                command:  ['sh', '-c', '${WSO2_SERVER_HOME}/bin/worker.sh stop']
          resources:
            requests:
              memory: 4Gi
              cpu: 2000m
            limits:
              memory: 4Gi
              cpu: 2000m
          imagePullPolicy: Always
          securityContext:
            runAsUser: 802
          ports:
            -
              containerPort: 9764
              protocol: "TCP"
            -
              containerPort: 9444
              protocol: "TCP"
            -
              containerPort: 7612
              protocol: "TCP"
            -
              containerPort: 7712
              protocol: "TCP"
            -
              containerPort: 9091
              protocol: "TCP"
            -
              containerPort: 7071
              protocol: "TCP"
            -
              containerPort: 7444
              protocol: "TCP"
          volumeMounts:
            - name: wso2am-pattern-1-am-analytics-worker-conf
              mountPath: /home/wso2carbon/wso2-config-volume/conf/worker/deployment.yaml
              subPath: deployment.yaml
      serviceAccountName: wso2am-pattern-1-svc-account
      imagePullSecrets:
        - name: wso2am-pattern-1-creds
      volumes:
        - name: wso2am-pattern-1-am-analytics-worker-conf
          configMap:
            name: wso2am-pattern-1-am-analytics-worker-conf
---
