apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2apim-with-analytics-apim-analytics-deployment
  namespace: "$ns.k8s.&.wso2.apim"
spec:
  replicas: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      deployment: wso2apim-with-analytics-apim-analytics
      product: wso2am
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: wso2apim-with-analytics-apim-analytics
        product: wso2am
    spec:
      containers:
        - name: wso2apim-with-analytics-apim-analytics
          image: docker.wso2.com/wso2am-analytics-worker:2.6.0
          resources:
            limits:
              memory: '2Gi'
            requests:
              memory: '2Gi'
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 7712
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 7712
            initialDelaySeconds: 10
            periodSeconds: 10
          lifecycle:
            preStop:
              exec:
                command:  ['sh', '-c', '/bin/worker.sh stop']
          imagePullPolicy: Always
          securityContext:
            runAsUser: 802
          ports:
            -
              containerPort: 9764
              protocol: 'TCP'
            -
              containerPort: 9444
              protocol: 'TCP'
            -
              containerPort: 7612
              protocol: 'TCP'
            -
              containerPort: 7712
              protocol: 'TCP'
            -
              containerPort: 9091
              protocol: 'TCP'
            -
              containerPort: 7071
              protocol: 'TCP'
            -
              containerPort: 7444
              protocol: 'TCP'
          volumeMounts:
            - name: apim-analytics-conf-worker
              mountPath: /home/wso2carbon/wso2-config-volume/conf/worker
      initContainers:
        - name: init-apim-with-analytics
          image: busybox
          command: ['sh', '-c', 'echo -e "checking for the availability of MySQL"; while ! nc -z wso2apim-with-analytics-rdbms-service 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL started";']
      serviceAccountName: 'wso2svc-account'
      imagePullSecrets:
        - name: wso2creds
      volumes:
        - name: apim-analytics-conf-worker
          configMap:
            name: apim-analytics-conf-worker
---
