# Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wso2apim-publisher
  labels:
    app: wso2apim-publisher
    node: publisher-local
    pattern: wso2apim-pattern-3
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wso2apim-publisher
        node: publisher-local
    spec:
      containers:
      - image: docker.wso2.com/wso2am-kubernetes:2.1.0
        name: wso2apim
        imagePullPolicy: IfNotPresent
        ports:
        -
          containerPort: 9763
          protocol: "TCP"
        -
          containerPort: 9443
          protocol: "TCP"
        volumeMounts:
        - name: apim-publisher-storage-volume
          mountPath: "/home/wso2user/wso2am-2.1.0/repository/deployment/server"
        - name: apim-publisher-bin
          mountPath: "/home/wso2user/wso2am-2.1.0-conf/bin/"
        - name: apim-publisher-conf
          mountPath: "/home/wso2user/wso2am-2.1.0-conf/conf/"
        - name: apim-publisher-identity
          mountPath: "/home/wso2user/wso2am-2.1.0-conf/conf-identity/"
        - name: apim-publisher-axis2
          mountPath: "/home/wso2user/wso2am-2.1.0-conf/conf-axis2/"
        - name: apim-publisher-datasources
          mountPath: "/home/wso2user/wso2am-2.1.0-conf/conf-datasources/"
        - name: apim-publisher-tomcat
          mountPath: "/home/wso2user/wso2am-2.1.0-conf/conf-tomcat/"
        livenessProbe:
          tcpSocket:
            port: 9443
          initialDelaySeconds: 90
          periodSeconds: 20
      serviceAccountName: "wso2svcacct"
      volumes:
      - name: apim-publisher-storage-volume
        persistentVolumeClaim:
          claimName: apim-publisher-volume-claim
      - name: apim-publisher-bin
        configMap:
          name: apim-publisher-bin
      - name: apim-publisher-conf
        configMap:
          name: apim-publisher-conf
      - name: apim-publisher-identity
        configMap:
          name: apim-publisher-identity
      - name: apim-publisher-axis2
        configMap:
          name: apim-publisher-axis2
      - name: apim-publisher-datasources
        configMap:
          name: apim-publisher-datasources
      - name: apim-publisher-tomcat
        configMap:
          name: apim-publisher-tomcat