# Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2apim-with-analytics-apim-analytics-deployment
  namespace : {{ .Values.kubernetes.namespace }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      deployment: wso2apim-with-analytics-apim-analytics
  template:
    metadata:
      labels:
        deployment: wso2apim-with-analytics-apim-analytics
    spec:
      initContainers:
        - name: init-apim-analytics-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z wso2apim-with-analytics-rdbms-service-mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL Server has started";']
        {{ if .Values.wso2.centralizedLogging.enabled }}
        - name: init-logstash-plugins-install
          image: docker.elastic.co/logstash/logstash:{{ default "7.2.0" .Values.wso2.centralizedLogging.logstash.imageTag }}
          command:
            - /bin/bash
            - "-c"
            - |
              set -e
              ./bin/logstash-plugin install logstash-codec-multiline logstash-filter-grok
          volumeMounts:
            - name: shared-plugins
              mountPath: /usr/share/logstash/plugins/
        - name: init-elasticsearch
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of Elasticsearch Server deployment"; while ! nc -z wso2-elasticsearch-master 9200; do sleep 1; printf "-"; done; echo -e "  >> Elasticsearch server has started";']
        {{ end }}
      containers:
        - name: wso2apim-with-analytics-apim-analytics
          {{- if or (eq .Values.wso2.subscription.username "") (eq .Values.wso2.subscription.password "") }}
          image: wso2/wso2am-analytics-worker:2.6.0
          {{- else }}
          image: docker.wso2.com/wso2am-analytics-worker:2.6.0
          {{- end }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 9444
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 9444
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 10
          lifecycle:
            preStop:
              exec:
                command:  ['sh', '-c', '${WSO2_SERVER_HOME}/bin/worker.sh stop']
          resources:
            requests:
              memory: "4Gi"
              cpu: "2000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          imagePullPolicy: Always
          securityContext:
            runAsUser: 802
          ports:
            -
              containerPort: 9764
              protocol: "TCP"
            -
              containerPort: 9444
              protocol: "TCP"
            -
              containerPort: 7612
              protocol: "TCP"
            -
              containerPort: 7712
              protocol: "TCP"
            -
              containerPort: 9091
              protocol: "TCP"
            -
              containerPort: 7071
              protocol: "TCP"
            -
              containerPort: 7444
              protocol: "TCP"
          volumeMounts:
            - name: apim-analytics-conf-worker
              mountPath: /home/wso2carbon/wso2-config-volume/conf/worker
        {{ if .Values.wso2.centralizedLogging.enabled }}
            - name: shared-logs
              mountPath: /home/wso2carbon/wso2am-analytics-2.6.0/wso2/worker/logs
        - name: wso2apim-with-analytics-logstash
          image: docker.elastic.co/logstash/logstash:{{ default "7.2.0" .Values.wso2.centralizedLogging.logstash.imageTag }}
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/share/logstash/wso2-logs/
            - name: logstash-yml
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
            - name: c5-logstash-conf
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
            - name: shared-plugins
              mountPath: /usr/share/logstash/plugins/
          env:
            - name: NODE_ID
              value: {{ default "wso2-apim-analytics-worker-node" .Values.wso2.centralizedLogging.logstash.indexNodeID.wso2ApimAnalyticsWorkerNode }}
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: logstash-elasticsearch-creds
                  key: username
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logstash-elasticsearch-creds
                  key: password
        {{ end }}
      serviceAccountName: "wso2svc-account"
      {{ if and (not (eq .Values.wso2.subscription.username "")) (not (eq .Values.wso2.subscription.password "")) }}
      imagePullSecrets:
        - name: wso2creds
      {{ end }}
      volumes:
        - name: apim-analytics-conf-worker
          configMap:
            name: apim-analytics-conf-worker
        {{ if .Values.wso2.centralizedLogging.enabled }}
        - name: shared-logs
          emptyDir: {}
        - name: logstash-yml
          configMap:
            name: logstash-yml
        - name: c5-logstash-conf
          configMap:
            name: c5-logstash-conf
        - name: shared-plugins
          emptyDir: {}
        - name: logstash-elasticsearch-creds
          secret:
            secretName: logstash-elasticsearch-creds
        {{ end }}
