# Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wso2apim-tm-1
  labels:
    app: wso2apim
    node: tm-1
    pattern: wso2apim-pattern-3
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wso2apim
        node: tm-1
    spec:
      containers:
      - image: docker.wso2.com/wso2am-kubernetes:2.1.0
        name: wso2apim
        imagePullPolicy: IfNotPresent
        ports:
        -
          containerPort: 5672
          protocol: "TCP"
        -
          containerPort: 9711
          protocol: "TCP"
        -
          containerPort: 9611
          protocol: "TCP"
        -
          containerPort: 7711
          protocol: "TCP"
        -
          containerPort: 7611
          protocol: "TCP"
        volumeMounts:
        -
          name: apim-tm1-storage-volume
          mountPath: "/home/wso2user/wso2am-2.1.0/repository/deployment/server"
        - name: apim-tm1-bin
          mountPath: "/home/wso2user/wso2am-2.1.0-conf/bin/"
        - name: apim-tm1-conf
          mountPath: "/home/wso2user/wso2am-2.1.0-conf/conf/"
        - name: apim-tm1-identity
          mountPath: "/home/wso2user/wso2am-2.1.0-conf/conf-identity/"
        livenessProbe:
          tcpSocket:
            port: 9443
          initialDelaySeconds: 90
          periodSeconds: 20
      serviceAccountName: "wso2svcacct"
      volumes:
      - name: apim-tm1-storage-volume
        persistentVolumeClaim:
          claimName: apim-tm1-volume-claim
      - name: apim-tm1-bin
        configMap:
          name: apim-tm1-bin
      - name: apim-tm1-conf
        configMap:
          name: apim-tm1-conf
      - name: apim-tm1-identity
        configMap:
          name: apim-tm1-identity