# Copyright (c) 2018, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: wso2am-pattern-1-am-1-datasources-conf
  namespace : {{ .Release.Namespace }}
data:
  {{- $apimgt_dburl := printf "%s%s%s%s%s" "jdbc:mysql://" .Values.wso2.mysql.host ":" .Values.wso2.mysql.port "/WSO2AM_APIMGT_DB?autoReconnect=true&amp;useSSL=false" }}
  {{- $am_dburl := printf "%s%s%s%s%s" "jdbc:mysql://" .Values.wso2.mysql.host ":" .Values.wso2.mysql.port "/WSO2AM_USER_DB?autoReconnect=true&amp;useSSL=false" }}
  {{- $reg_dburl := printf "%s%s%s%s%s" "jdbc:mysql://" .Values.wso2.mysql.host ":" .Values.wso2.mysql.port "/WSO2AM_REG_DB?autoReconnect=true&amp;useSSL=false" }}
  {{- $db_driver_class_name := .Values.wso2.mysql.driverClass }}
  {{- $db_validation_query := .Values.wso2.mysql.validationQuery }}
  {{- $db_username := .Values.wso2.mysql.username }}
  {{- $db_password := .Values.wso2.mysql.password }}
  {{- $file := .Files }}
  {{- range $path, $byte := .Files.Glob "confs/am-1/datasources/*" }}
  {{- $list := $path | splitList "/"}}
  {{- $length := len $list }}
  {{- $last := add $length -1 }}
  {{ index $list $last }}: |-
      {{- range $line := $file.Lines $path }}
      {{ $line | replace "{{ DB_USERNAME }}" $db_username | replace "{{ DB_PASSWORD }}" $db_password | replace "{{ AMDB_URL }}" $am_dburl | replace "{{ APIMGT_DB_URL }}" $apimgt_dburl | replace "{{ REG_DB_URL }}" $reg_dburl | replace "{{ DRIVER_CLASSNAME }}" $db_driver_class_name | replace "{{ VALIDATION_QUERY }}" $db_validation_query }}
      {{- end }}
  {{- end }}
