# Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "am-pattern-3.resource.prefix" . }}-am-gateway-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.wso2.deployment.am.gateway.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.wso2.deployment.am.gateway.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.wso2.deployment.am.gateway.strategy.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  selector:
    matchLabels:
      deployment: {{ template "am-pattern-3.resource.prefix" . }}-am-gateway
  template:
    metadata:
      annotations:
        checksum.am.gw.conf: {{ include (print $.Template.BasePath "/am/gateway/wso2am-pattern-3-am-gateway-conf.yaml") . | sha256sum }}
      labels:
        deployment: {{ template "am-pattern-3.resource.prefix" . }}-am-gateway
        product: apim
    spec:
      initContainers:
        - name: init-cp
          image: busybox:1.32
          command: ['sh', '-c', 'echo -e "Checking for the availability of Control Plane deployment"; while ! nc -z {{ template "am-pattern-3.resource.prefix" . }}-am-cp-service 9443; do sleep 1; printf "-"; done; echo -e "  >> Control Plane has started";']
      containers:
      - name: wso2am-gateway
{{- include "image" (dict "Values" .Values "deployment" .Values.wso2.deployment.am) | indent 8 }}
        imagePullPolicy: {{ .Values.wso2.deployment.am.imagePullPolicy }}
        env:
        - name: PROFILE_NAME
          value: gateway-worker
        - name: NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: JVM_MEM_OPTS
          value: "-Xms{{ .Values.wso2.deployment.am.resources.jvm.heap.memory.xms }} -Xmx{{ .Values.wso2.deployment.am.resources.jvm.heap.memory.xmx }}"
        startupProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - nc -z localhost 8243
          initialDelaySeconds: {{ .Values.wso2.deployment.am.startupProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.wso2.deployment.am.startupProbe.periodSeconds }}
          failureThreshold: {{ .Values.wso2.deployment.am.startupProbe.failureThreshold }}
        livenessProbe:
          httpGet:
              path: /services/Version
              port: 9763
          periodSeconds: {{ .Values.wso2.deployment.am.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
              path: /services/Version
              port: 9763
          initialDelaySeconds: {{ .Values.wso2.deployment.am.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.wso2.deployment.am.readinessProbe.periodSeconds }}
        lifecycle:
          preStop:
            exec:
              command:  ['sh', '-c', '${WSO2_SERVER_HOME}/bin/api-manager.sh stop']
        resources:
          requests:
            memory: {{ .Values.wso2.deployment.am.resources.requests.memory }}
            cpu: {{ .Values.wso2.deployment.am.resources.requests.cpu }}
          limits:
            memory: {{ .Values.wso2.deployment.am.resources.limits.memory }}
            cpu: {{ .Values.wso2.deployment.am.resources.limits.cpu }}
        securityContext:
          runAsUser: 802
        ports:
        - containerPort: 8280
          protocol: TCP
        - containerPort: 8243
          protocol: TCP
        - containerPort: 9763
          protocol: TCP
        - containerPort: 9443
          protocol: TCP
        volumeMounts:
        - name: wso2am-gateway-conf
          mountPath: /home/wso2carbon/wso2-config-volume/repository/conf
      serviceAccountName: {{ .Values.kubernetes.serviceAccount }}
      {{- if .Values.wso2.deployment.am.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.wso2.deployment.am.imagePullSecrets }}
      {{- else if and (not (eq .Values.wso2.subscription.username "")) (not (eq .Values.wso2.subscription.password "")) }}
      imagePullSecrets:
        - name: {{ template "am-pattern-3.resource.prefix" . }}-wso2-private-registry-creds
      {{ end }}
      volumes:
      - name: wso2am-gateway-conf
        configMap:
          name: {{ template "am-pattern-3.resource.prefix" . }}-am-gateway-conf
