username: "<USERNAME>"
password: "<PASSWORD>"
email: "<EMAIL>"

namespace: "wso2"
svcaccount: "wso2svc-account"
serverIp: "<SERVER_IP>"
sharedDeploymentLocationPath: "<NFS_LOCATION>"
isKMLocationPath: "<NFS_LOCATION>"



