# Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

wso2:
  # WSO2 subscription parameters. If you do not have an active subscription, do not provide values for the parameters.
  # If you do not possess an active WSO2 subscription already, you can sign up for a WSO2 Free Trial Subscription at (https://wso2.com/free-trial-subscription).
  subscription:
    username: ""
    password: ""

  deployment:
    dependencies:
      # The configuration should be set to be 'true' if a MySQL database should be spawned as a pod within the cluster
      mysql: true
      # Enable NFS dynamic provisioner for Kubernetes
      nfsServerProvisioner: true

    persistentRuntimeArtifacts:
      # Persistent storage provider expected to be used for sharing persistent runtime artifacts
      # Must refer to an appropriate Kubernetes Storage Class (https://kubernetes.io/docs/concepts/storage/storage-classes/)
      # "nfs" (default) - Using the official Kubernetes NFS Server Provisioner (https://github.com/helm/charts/tree/master/stable/nfs-server-provisioner).
      # This provisioner is installed by default, with this Helm Chart (wso2 -> deployment -> dependencies -> nfsServerProvisioner).
      storageClass: &storageClass "nfs"
      capacity:
        sharedSynapseConfigs: 50M
        sharedExecutionPlans: 20M
        carbonDatabase: 50M
        solrIndexedData: 50M

    analytics:
      dashboard:
        # Hostname for API Manager Analytics Dashboard
        hostname: "analytics.am.wso2.com"
        # If a custom image must be used, uncomment 'dockerRegistry' and provide its value.
#        dockerRegistry: ""
        imageName: "wso2am-analytics-dashboard"
        imageTag: "3.1.0"
        # Refer to the Kubernetes documentation on updating images (https://kubernetes.io/docs/concepts/containers/images/#updating-images)
        imagePullPolicy: Always

        # Number of deployment replicas
        replicas: 1
        strategy:
          rollingUpdate:
            # The maximum number of pods that can be scheduled above the desired number of pods.
            maxSurge: 1
            # The maximum number of pods that can be unavailable during the update.
            maxUnavailable: 0
        # Indicates whether the container is running.
        livenessProbe:
          # Number of seconds after the container has started before liveness probes are initiated.
          initialDelaySeconds: 20
          # How often (in seconds) to perform the probe.
          periodSeconds: 10
        # Indicates whether the container is ready to service requests.
        readinessProbe:
          # Number of seconds after the container has started before readiness probes are initiated.
          initialDelaySeconds: 20
          # How often (in seconds) to perform the probe.
          periodSeconds: 10
#        # If the deployment configurations for the Dashboard profile of WSO2 API Manager Analytics v3.1.0 (<WSO2AM_ANALYTICS>/conf/dashboard/deployment.yaml),
#        # add the customized configuration file under (wso2 -> deployment -> analytics -> dashboard -> config -> deployment.yaml)
#        config:
#          deployment.yaml: |-
#            # deployment configurations for the Dashboard profile of WSO2 API Manager Analytics v3.1.0 (<WSO2AM_ANALYTICS>/conf/dashboard/deployment.yaml)
        resources:
          # These are the minimum resource recommendations for running WSO2 Stream Processor based server profiles
          # as per official documentation (https://docs.wso2.com/display/SP440/Installation+Prerequisites).
          requests:
            memory: "4Gi"
            cpu: "2000m"
          # Please see the official documentation on WSO2 Stream Processor based Performance Analysis and Resource recommendations
          # (https://docs.wso2.com/display/SP440/Performance+Analysis+Results) and tune the limits according to your needs
          # where necessary.
          limits:
            memory: "4Gi"
            cpu: "2000m"

      worker:
        # If a custom image must be used, uncomment 'dockerRegistry' and provide its value.
#        dockerRegistry: ""
        imageName: "wso2am-analytics-worker"
        imageTag: "3.1.0"
        # Refer to the Kubernetes documentation on updating images (https://kubernetes.io/docs/concepts/containers/images/#updating-images)
        imagePullPolicy: Always
        # Indicates whether the container is running.
        livenessProbe:
          # Number of seconds after the container has started before liveness probes are initiated.
          initialDelaySeconds: 20
          # How often (in seconds) to perform the probe.
          periodSeconds: 10
        # Indicates whether the container is ready to service requests.
        readinessProbe:
          # Number of seconds after the container has started before readiness probes are initiated.
          initialDelaySeconds: 20
          # How often (in seconds) to perform the probe.
          periodSeconds: 10
#        # If the deployment configurations for the Worker profile of WSO2 API Manager Analytics v3.1.0 (<WSO2AM_ANALYTICS>/conf/worker/deployment.yaml),
#        # add the customized configuration file under (wso2 -> deployment -> analytics -> worker -> config -> deployment.yaml)
#        config:
#          deployment.yaml: |-
#            # deployment configurations for the Worker profile of WSO2 API Manager Analytics v3.1.0 (<WSO2AM_ANALYTICS>/conf/worker/deployment.yaml)
        resources:
          # These are the minimum resource recommendations for running WSO2 Stream Processor based server profiles
          # as per official documentation (https://docs.wso2.com/display/SP440/Installation+Prerequisites).
          requests:
            memory: "4Gi"
            cpu: "2000m"
          # Please see the official documentation on WSO2 Stream Processor based Performance Analysis and Resource recommendations
          # (https://docs.wso2.com/display/SP440/Performance+Analysis+Results) and tune the limits according to your needs
          # where necessary.
          limits:
            memory: "4Gi"
            cpu: "2000m"

    am:
      # If a custom image must be used, uncomment 'dockerRegistry' and provide its value.
#      dockerRegistry: ""
      imageName: "wso2am"
      imageTag: "3.1.0"
      # Refer to the Kubernetes documentation on updating images (https://kubernetes.io/docs/concepts/containers/images/#updating-images)
      imagePullPolicy: Always

      # API Manager's Gateway specific configurations
      gateway:
        # Hostname for Gateway profile
        hostname: "gateway.am.wso2.com"
        # Number of deployment replicas
        replicas: 2
        strategy:
          rollingUpdate:
            # The maximum number of pods that can be scheduled above the desired number of pods.
            maxSurge: 2
            # The maximum number of pods that can be unavailable during the update.
            maxUnavailable: 0
#        # If the deployment configurations for the Gateway profile of WSO2 API Manager v3.1.0 (<WSO2AM>/repository/conf/deployment.toml),
#        # add the customized configuration file under (wso2 -> deployment -> am -> gateway -> config -> deployment.toml)
#        config:
#          deployment.toml: |-
#            # deployment configurations for the Gateway profile of WSO2 API Manager v3.1.0 (<WSO2AM>/repository/conf/deployment.toml)

      # API Manager's Key Manager specific configurations
      km:
        # Number of deployment replicas
        replicas: 2
        strategy:
          rollingUpdate:
            # The maximum number of pods that can be scheduled above the desired number of pods.
            maxSurge: 2
            # The maximum number of pods that can be unavailable during the update.
            maxUnavailable: 0
#        # If the deployment configurations for the Key Manager profile of WSO2 API Manager v3.1.0 (<WSO2AM>/repository/conf/deployment.toml),
#        # add the customized configuration file under (wso2 -> deployment -> am -> km -> config -> deployment.toml)
#        config:
#          deployment.toml: |-
#            # deployment configurations for the Key Manager profile of WSO2 API Manager v3.1.0 (<WSO2AM>/repository/conf/deployment.toml)

      # API Manager's Publisher specific configurations
      publisher:
        # Hostname for Publisher profile
        hostname: "publisher.am.wso2.com"
#        # If the deployment configurations for the Publisher profile of WSO2 API Manager v3.1.0 (<WSO2AM>/repository/conf/deployment.toml),
#        # add the customized configuration file under (wso2 -> deployment -> am -> km -> config -> deployment.toml)
#        config:
#          deployment.toml: |-
#            # deployment configurations for the Publisher profile of WSO2 API Manager v3.1.0 (<WSO2AM>/repository/conf/deployment.toml)

      # API Manager's DevPortal specific configurations
      devportal:
        # Hostname for DevPortal profile
        hostname: "devportal.am.wso2.com"
#        # If the deployment configurations for the DevPortal profile of WSO2 API Manager v3.1.0 (<WSO2AM>/repository/conf/deployment.toml),
#        # add the customized configuration file under (wso2 -> deployment -> am -> km -> config -> deployment.toml)
#        config:
#          deployment.toml: |-
#            # deployment configurations for the DevPortal profile of WSO2 API Manager v3.1.0 (<WSO2AM>/repository/conf/deployment.toml)

      # API Manager's Traffic Manager specific configurations
      tm:
        # If the deployment configurations for the Traffic Manager profile of WSO2 API Manager v3.1.0 (<WSO2AM>/repository/conf/deployment.toml),
        # add the customized configuration file under (wso2 -> deployment -> am -> pubStoreTM -> instanceOne -> config -> deployment.toml)
        config: ""
#          deployment.toml: |-
#            # deployment configurations for the Traffic Manager profile of WSO2 API Manager v3.1.0 (<WSO2AM>/repository/conf/deployment.toml)

      # Indicates whether the container is running.
      livenessProbe:
        # Number of seconds after the container has started before liveness probes are initiated.
        initialDelaySeconds: 60
        # How often (in seconds) to perform the probe.
        periodSeconds: 10
        # Indicates whether the container is ready to service requests.
      readinessProbe:
        # Number of seconds after the container has started before readiness probes are initiated.
        initialDelaySeconds: 60
        # How often (in seconds) to perform the probe.
        periodSeconds: 10

      resources:
        # These are the resource recommendations for running WSO2 API Management product profiles with profile optimization.
        requests:
          memory: "1Gi"
          cpu: "1000m"
        limits:
          memory: "2Gi"
          cpu: "2000m"

kubernetes:
  # Name of Kubernetes service account
  serviceAccount: "wso2am-pattern-3-svc-account"

mysql-am:
  mysql:
    persistence:
      storageClass: *storageClass
