# Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: Service
metadata:
  name: wso2am-analytics-pattern-1
  labels:
    app: wso2am-analytics-pattern-1
    tier: wso2am-analytics-pattern-1
spec:
  type: NodePort
  ports:
    # ports that this service should serve on
    -
      name: 'pass-through-http'
      port: 8280
      targetPort: 8280
      nodePort: 32006
    -
      name: 'pass-through-https'
      port: 8243
      targetPort: 8243
      nodePort: 32007
    -
      name: 'servlet-http'
      port: 9763
      targetPort: 9763
      nodePort: 32008
    -
      name: 'servlet-https'
      port: 9443
      targetPort: 9443
      nodePort: 32009
    -
      name: 'thrift-http'
      port: 7612
      targetPort: 7612
      nodePort: 32010
    -
      name: 'thrift-https'
      port: 7712
      targetPort: 7712
      nodePort: 32011
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: wso2am-analytics-pattern-1
    tier: wso2am-analytics-pattern-1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wso2am-analytics-pattern-1
  labels:
    app: wso2am-analytics-pattern-1
    tier: wso2am-analytics-pattern-1
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wso2am-analytics-pattern-1
        tier: wso2am-analytics-pattern-1
    spec:
      containers:
      - image: us.gcr.io/steam-talent-167709/wso2am-analytics-kubernetes-pattern-1:2.1.0
        name: wso2am-analytics-pattern-1
        ports:
        -
          containerPort: 8280
          protocol: "TCP"
        -
          containerPort: 8243
          protocol: "TCP"
        -
          containerPort: 9763
          protocol: "TCP"
        -
          containerPort: 9443
          protocol: "TCP"
        -
          containerPort: 7612
          protocol: "TCP"
        -
          containerPort: 7712
          protocol: "TCP"