# Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apim-rdbms-deployment
  labels:
    app: apim-rdbms
    pattern: wso2apim-pattern-1
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: apim-rdbms
        tier: apim-rdbms
        pattern: wso2apim-pattern-1
    spec:
      containers:
      - image: docker.wso2.com/apim-rdbms-kubernetes:2.1.0
        name: apim-rdbms
        imagePullPolicy: IfNotPresent
        env:
          -
            name: MYSQL_ROOT_PASSWORD
            value: root
        ports:
        - containerPort: 3306
          name: apim-rdbms
        volumeMounts:
        - name: apim-rdbms-persistent-storage
          mountPath: /var/lib/mysql
        args: ["--max-connections", "10000"]
      volumes:
      - name: apim-rdbms-persistent-storage
        persistentVolumeClaim:
          claimName: apim-rdbms-volume-claim
      serviceAccountName: "wso2svcacct"
