# Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2am-pattern-2-pub-store-tm-2-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  minReadySeconds: {{ .Values.wso2.deployment.am..pubStoreTM.minReadySeconds }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      deployment: wso2am-pattern-2-pub-store-tm
      node: wso2am-pattern-2-pub-store-tm-2
  template:
    metadata:
      labels:
        deployment: wso2am-pattern-2-pub-store-tm
        node: wso2am-pattern-2-pub-store-tm-2
    spec:
      initContainers:
      {{- if and .Values.wso2.deployment.db.host (.Values.wso2.deployment.db.port) }}
      - name: init-apim-db
        image: busybox:1.31
        command: ['sh', '-c', 'echo -e "Checking for the availability of DBMS service"; while ! nc -z {{ .Values.wso2.deployment.db.host }} {{ .Values.wso2.deployment.db.port }}; do sleep 1; printf "-"; done; echo -e "  >> DBMS service is available";']
      {{- end }}
      - name: init-apim-analytics
        image: busybox:1.31
        command: ['sh', '-c', 'echo -e "Checking for the availability of WSO2 API Manager Analytics Worker deployment"; while ! nc -z wso2am-pattern-2-am-analytics-worker-service 7712; do sleep 1; printf "-"; done; echo -e "  >> WSO2 API Manager Analytics Worker has started";']
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "{{ .Release.Name }}-am"
      containers:
        - name: wso2am-pub-store-tm
          {{- if .Values.wso2.deployment.am.dockerRegistry }}
          image: {{ .Values.wso2.deployment.am.dockerRegistry }}/{{ .Values.wso2.deployment.am.imageName }}
          {{- $tag := .Values.wso2.deployment.am.imageTag }}
          {{- if not (eq $tag "") }}{{- printf ":%s" $tag -}}{{- end }}
          {{- else if or (eq .Values.wso2.subscription.username "") (eq .Values.wso2.subscription.password "") }}
          image: chathuru/{{ .Values.wso2.deployment.am.imageName }}:{{ .Values.wso2.deployment.am.imageTag }}
          {{- else }}
          image: docker.wso2.com/{{ .Values.wso2.deployment.am.imageName }}:{{ .Values.wso2.deployment.am.imageTag }}
          {{- end }}
          env:
          - name: HOST_NAME
            value: "{{ .Release.Name }}-am"
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 9443
            initialDelaySeconds: {{ .Values.wso2.deployment.am.pubStoreTM.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.wso2.deployment.am.pubStoreTM.livenessProbe.periodSeconds }}
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 9443
            initialDelaySeconds: {{ .Values.wso2.deployment.am.pubStoreTM.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.wso2.deployment.am.pubStoreTM.readinessProbe.periodSeconds }}
          lifecycle:
            preStop:
              exec:
                command:  ['sh', '-c', '${WSO2_SERVER_HOME}/bin/wso2server.sh stop']
          resources:
            requests:
              memory: {{ .Values.wso2.deployment.am.resources.requests.memory }}
              cpu: {{ .Values.wso2.deployment.am.resources.requests.cpu }}
            limits:
              memory: {{ .Values.wso2.deployment.am.resources.limits.memory }}
              cpu: {{ .Values.wso2.deployment.am.resources.limits.cpu }}
          imagePullPolicy: {{ .Values.wso2.deployment.am.imagePullPolicy }}
          securityContext:
            runAsUser: 802
          ports:
          - containerPort: 9763
            protocol: "TCP"
          - containerPort: 9443
            protocol: "TCP"
          - containerPort: 5672
            protocol: "TCP"
          - containerPort: 9711
            protocol: "TCP"
          - containerPort: 9611
            protocol: "TCP"
          - containerPort: 7711
            protocol: "TCP"
          - containerPort: 7611
            protocol: "TCP"
          volumeMounts:
          - name: wso2am-pattern-2-storage-volume
            mountPath: /home/wso2carbon/wso2am-3.0.0/repository/deployment/server/executionplans
          - name: wso2am-pattern-2-pub-store-tm-2-conf
            mountPath: /home/wso2carbon/wso2-config-volume/repository/conf/deployment.toml
            subPath: deployment.toml
          - name: wso2am-pattern-2-am-conf-entrypoint
            mountPath: /home/wso2carbon/docker-entrypoint.sh
            subPath: docker-entrypoint.sh
      serviceAccountName: {{ .Values.kubernetes.serviceAccount }}
      {{- if .Values.wso2.deployment.am.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.wso2.deployment.am.imagePullSecrets }}
      {{- else if and (not (eq .Values.wso2.subscription.username "")) (not (eq .Values.wso2.subscription.password "")) }}
      imagePullSecrets:
        - name: wso2am-pattern-2-wso2-private-registry-creds
      {{ end }}
      volumes:
      - name: wso2am-pattern-2-storage-volume
        persistentVolumeClaim:
          claimName: wso2am-pattern-2-pub-store-tm-shared-executionplans-volume-claim
      - name: wso2am-pattern-2-pub-store-tm-2-conf
        configMap:
          name: wso2am-pattern-2-pub-store-tm-2-conf
      - name: wso2am-pattern-2-am-conf-entrypoint
        configMap:
          name: wso2am-pattern-2-am-conf-entrypoint
          defaultMode: 0407
