[server]
hostname = "$env{HOST_NAME}"
node_ip = "$env{NODE_IP}"
server_role = "gateway-worker"
offset = "0"

[user_store]
type = "database"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.shared_db]
type = "h2"
url = "jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE"
username = "wso2carbon"
password = "wso2carbon"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"
# key manager implementation

[apim.key_manager]
service_url = "https://wso2am-pattern-2-km-service:${mgt.transport.https.port}/services/"
username= "$ref{super_admin.username}"
password= "$ref{super_admin.password}"
# Traffic Manager configurations

[apim.throttling]
username= "$ref{super_admin.username}"
password= "$ref{super_admin.password}"
enable_unlimited_tier = true
enable_header_based_throttling = false
enable_jwt_claim_based_throttling = false
enable_query_param_based_throttling = false
throttle_decision_endpoints = ["tcp://wso2am-pattern-2-pub-store-tm-1-service:5672","tcp://wso2am-pattern-2-pub-store-tm-2-service:5672"]

[[apim.throttling.url_group]]
traffic_manager_urls = ["tcp://wso2am-pattern-2-pub-store-tm-1-service:9611"]
traffic_manager_auth_urls = ["ssl://wso2am-pattern-2-pub-store-tm-1-service:9711"]
type = "loadbalance"

[[apim.throttling.url_group]]
traffic_manager_urls = ["tcp://wso2am-pattern-2-pub-store-tm-2-service:9611"]
traffic_manager_auth_urls = ["ssl://wso2am-pattern-2-pub-store-tm-2-service:9711"]
type = "loadbalance"

[transport.https.properties]
proxyPort = 443

[apim.analytics]
enable = "True"
username= "$ref{super_admin.username}"
password= "$ref{super_admin.password}"
store_api_url = "https://wso2am-pattern-2-am-analytics-worker-service:7444"
store_api_username = "${admin.username}"
store_api_password = "${admin.password}"

[[apim.analytics.url_group]]
analytics_url =["tcp://wso2am-pattern-2-analytics-worker-service:7612","tcp://wso2am-pattern-2-analytics-worker-2-service:7612"]
analytics_auth_url =["ssl://wso2am-pattern-2-analytics-worker-service:7712","ssl://wso2am-pattern-2-analytics-worker-2-service:7712"]
type = "failover"

[apim.cache.gateway_token]
enable = true
expiry_time = 15

[apim.cache.resource]
enable = true

[apim.oauth_config]
remove_outbound_auth_header = true
auth_header = "Authorization"

[apim.cors]
allow_origins = "*"
allow_methods = ["GET","PUT","POST","DELETE","PATCH","OPTIONS"]
allow_headers = ["authorization","Access-Control-Allow-Origin","Content-Type","SOAPAction"]
allow_credentials = false
